server:
  port: 8081
  servlet:
    context-path: /api/v1


springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/Tasks
          jwk-set-uri: http://localhost:8080/auth/realms/Tasks/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://localhost:5433/tasks
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.xml
